import type { Video } from '@/types'

export const MOCK_VIDEOS: Video[] = [
  {
    id: '1',
    code: 'SONE-001',
    title: '인기 시리즈의 첫 번째 작품',
    files: [{ path: 'C:/Videos/SONE-001.mp4', size: 1_000_000 }],
    thumbnailPath: null,
    actors: ['아오이 레나'],
    series: 'SONE',
    tags: ['단독', '미소녀'],
    duration: 7200,
    watched: true,
    favorite: true,
    addedAt: '2026-03-01T10:00:00Z',
    releasedAt: '2026-01-15',
    scrapeStatus: 'not_scraped' as const,
    scrapedAt: null,
    makerName: 'S1 No.1 Style',
  },
  {
    id: '2',
    code: 'MIDE-456',
    title: '두 번째 목업 작품 제목이 여기에 들어갑니다',
    files: [{ path: 'C:/Videos/MIDE-456.mp4', size: 1_000_000 }],
    thumbnailPath: null,
    actors: ['사쿠라 모모'],
    series: 'MIDE',
    tags: ['직장물', '미소녀'],
    duration: 5400,
    watched: false,
    favorite: false,
    addedAt: '2026-03-05T12:00:00Z',
    releasedAt: '2026-02-01',
    scrapeStatus: 'not_scraped' as const,
    scrapedAt: null,
    makerName: 'MediaStation',
  },
  {
    id: '3',
    code: 'IPX-789',
    title: '세 번째 작품 타이틀',
    files: [{ path: 'C:/Videos/IPX-789.mp4', size: 1_000_000 }],
    thumbnailPath: null,
    actors: ['하나 하루카', '아오이 레나'],
    series: null,
    tags: ['기획물'],
    duration: 9000,
    watched: false,
    favorite: true,
    addedAt: '2026-03-10T08:00:00Z',
    releasedAt: '2026-02-20',
    scrapeStatus: 'not_scraped' as const,
    scrapedAt: null,
    makerName: 'IdeaPocket',
  },
  {
    id: '4',
    code: 'SONE-002',
    title: '인기 시리즈 두 번째',
    files: [{ path: 'C:/Videos/SONE-002.mp4', size: 1_000_000 }],
    thumbnailPath: null,
    actors: ['아오이 레나'],
    series: 'SONE',
    tags: ['단독', '기획물'],
    duration: 6300,
    watched: false,
    favorite: false,
    addedAt: '2026-03-15T09:00:00Z',
    releasedAt: '2026-03-01',
    scrapeStatus: 'not_scraped' as const,
    scrapedAt: null,
    makerName: 'S1 No.1 Style',
  },
  {
    id: '5',
    code: 'ABW-100',
    title: '다섯 번째 작품',
    files: [{ path: 'C:/Videos/ABW-100.mp4', size: 1_000_000 }],
    thumbnailPath: null,
    actors: ['사쿠라 모모'],
    series: null,
    tags: ['미소녀', '솔로'],
    duration: 4800,
    watched: true,
    favorite: false,
    addedAt: '2026-03-20T14:00:00Z',
    releasedAt: '2026-03-10',
    scrapeStatus: 'not_scraped' as const,
    scrapedAt: null,
    makerName: 'Antbee',
  },
  {
    id: '6',
    code: 'MIDV-200',
    title: '여섯 번째 목업 영상',
    files: [{ path: 'C:/Videos/MIDV-200.mp4', size: 1_000_000 }],
    thumbnailPath: null,
    actors: ['하나 하루카'],
    series: 'MIDE',
    tags: ['직장물'],
    duration: 5700,
    watched: false,
    favorite: false,
    addedAt: '2026-03-25T11:00:00Z',
    releasedAt: '2026-03-15',
    scrapeStatus: 'not_scraped' as const,
    scrapedAt: null,
    makerName: 'MediaStation',
  },
  {
    id: '7',
    code: 'STARS-300',
    title: '일곱 번째 작품 제목',
    files: [{ path: 'C:/Videos/STARS-300.mp4', size: 1_000_000 }],
    thumbnailPath: null,
    actors: ['미즈키 아이'],
    series: null,
    tags: ['기획물', '단독'],
    duration: 8100,
    watched: false,
    favorite: true,
    addedAt: '2026-04-01T10:00:00Z',
    releasedAt: '2026-03-25',
    scrapeStatus: 'not_scraped' as const,
    scrapedAt: null,
    makerName: 'Rocket',
  },
  {
    id: '8',
    code: 'JUL-400',
    title: '여덟 번째 목업',
    files: [{ path: 'C:/Videos/JUL-400.mp4', size: 1_000_000 }],
    thumbnailPath: null,
    actors: ['미즈키 아이', '사쿠라 모모'],
    series: null,
    tags: ['기획물'],
    duration: 6600,
    watched: true,
    favorite: false,
    addedAt: '2026-04-05T09:00:00Z',
    releasedAt: '2026-04-01',
    scrapeStatus: 'not_scraped' as const,
    scrapedAt: null,
    makerName: 'Madonna',
  },
]
